### ISSUE TITLE
Comments to readme

### ISSUE THREAD

**Issue by tonnitommi** [robocorp/example-oauth-email#4]
https://github.com/robocorp/example-oauth-email/blob/ffc1f9849ac671bd0e8dfdf9ad8231b299b0e5cb/README.md?plain=1#L2

It would help to have a few words in the beginning of what the example shows users. "With this example you will learn to X and Y."

https://github.com/robocorp/example-oauth-email/blob/ffc1f9849ac671bd0e8dfdf9ad8231b299b0e5cb/README.md?plain=1#L17

It's a bit confusing as the vault is mentioned two times. First here, and then later in the step 2. I would write here only "Take a note of the client id and secret as you'll need them soon"

https://github.com/robocorp/example-oauth-email/blob/ffc1f9849ac671bd0e8dfdf9ad8231b299b0e5cb/README.md?plain=1#L24

This could be already in the beginning before creating the credentials: "first check that Gmail API is enabled".

https://github.com/robocorp/example-oauth-email/blob/ffc1f9849ac671bd0e8dfdf9ad8231b299b0e5cb/README.md?plain=1#L86

Copy-pasting the URL from console seems to work, so that should be described here. The browser that is opened by the automation does not let me authenticate, as maybe Google blocks something?

https://github.com/robocorp/example-oauth-email/blob/ffc1f9849ac671bd0e8dfdf9ad8231b299b0e5cb/README.md?plain=1#L87

This could have a screenshot example of what I should be looking for. 

https://github.com/robocorp/example-oauth-email/blob/ffc1f9849ac671bd0e8dfdf9ad8231b299b0e5cb/README.md?plain=1#L89

The first bullet (You should see...) could be lower as it's the result of the process. I went and ran the process first, and only later realised that I should have configured the user name. :) So that should be the first bullet.

**Comment by cmin764** [comment]
Thank you for the feedback, will take care of these!
